### ISSUE TITLE
Eu, como Organizador, quero saber quem preencheu todas as notas dos alunos na 1ª fase da OPI

### ISSUE THREAD

**Issue by erijonhson** [olimpiada-paraibana-de-informatica/backend#11]
**Requisitos**
Quando Delegado indicar que terminou de cadastrar todas as notas dos Estudantes de sua Escola, Lista de Interesse deve receber e-mail informando detalhes dessa ação.

**Tasks**
- [x] CRUD para Lista de Interesse
   - [x] Model
   - [x] Repository
   - [x] Service
   - [x] Controller
- [x] Envio de e-mail para Lista de Interesse sempre que um Delegado indicar que preencheu todas as notas dos Alunos de sua Escola 
- [x] Estratégia para verificar quando o Delegado postou todas as notas dos Alunos
