### ISSUE TITLE
Eu, como Organizador, quero gerar Lista de Classificados para a 2ª fase da OPI a partir de uma lista de Alunos organizada de forma decrescente por nota obtida

### ISSUE THREAD

**Issue by erijonhson** [olimpiada-paraibana-de-informatica/backend#12]
**Requisitos**
Para iniciar a 2ª fase da OPI, será preciso indicar ao Sistema para processar os Competidores e decidir quais vão para a 2ª fase e quais não vão mediante % a ser definida no momento do cálculo.

**Tasks**
- [x] Repository & Service & Controller
   - [x] atualizar Competidores, marcando-os com APROVADO|REPROVADO para 2º fase de acordo com % requerida
   - [x] recuperar Competidores filtrando por marcação APROVADO|REPROVADO
