### ISSUE TITLE
Listas de Classificados deve ser feita agrupadas por Categorias

### ISSUE THREAD

**Issue by erijonhson** [olimpiada-paraibana-de-informatica/backend#17]
**Requisitos**
Deve haver muitas listas de classificados para segunda fase, sendo uma lista para cada Categoria da Olimpíada.

**Tasks**
- [x] lista de classificados para Categoria Iniciação 1
- [x] lista de classificados para Categoria Iniciação 1 Escolas Públicas
- [x] lista de classificados para Categoria Iniciação 2
- [x] lista de classificados para Categoria Iniciação 2 Escolas Públicas
- [x] lista de classificados para Categoria Programação
