### ISSUE TITLE
Categorias Iniciação 1 e Iniciação 2

### ISSUE THREAD

**Issue by erijonhson** [olimpiada-paraibana-de-informatica/backend#18]
**Requisitos**
Categorias Iniciação 1 e Iniciação 2 devem ser únicas. Decidir se é de Escola Pública ou não deve ser avaliado conforme Tipo de Escola participante.

**Tasks**
- [x] Remover Categoria Iniciação 1 Escolas Públicas
- [x] Remover Categoria Iniciação 2 Escolas Públicas
- [x] Garantir que a distinção entre Escolas Públicas ou Privadas sejam feitas automaticamente nos momentos adequados (classificação para segunda fase, por exemplo)
