### ISSUE TITLE
Auditoria com Envers

### ISSUE THREAD

**Issue by erijonhson** [olimpiada-paraibana-de-informatica/backend#4]
**Requisitos**
Eu, como Administrador, quero auditar o sistema de maneira a avaliar as modificações feitas, para manter controle de modificações.

**Tasks**
- [ ] Adicionar Envers ao projeto
- [ ] Habilitar auditoria para todos os models/tabelas
- [ ] Service (ao menos de Escolas, como exemplo)
- [ ] Endpoint (ao menos de Escolas, como exemplo)
- [ ] DTO (ao menos de Escolas, como exemplo)
