### ISSUE TITLE
Delegado deve ter acesso apenas à Escola com ele relacionada

### ISSUE THREAD

**Issue by erijonhson** [olimpiada-paraibana-de-informatica/backend#5]
**Requisitos**
Delegado deve ter acesso (visualizar e editar) apenas Escola com ele relacionada. Apenas administrador pode deletar conta do Delegado/Escola. Nesse último caso, o Delegado requisita ao Administrador para fazê-lo. 

**Tasks**
- [ ] Controller Escola
  - [x] utilizar o Principal<sup>*</sup> para recuperar (show) Escola relacionada. Acessar via privilégio SA_SC (Show Associated School)
  - [x] utilizar o Principal<sup>*</sup> para editar (show) Escola relacionada. Acessar via privilégio UA_SC (Update Associated School)
  - [ ] utilizar o Principal<sup>*</sup> para avisar aos Administradores que determinado Delegado quer ter sua conta excluída
- [ ] Service Escola
  - [x] buscar (show) Escola pelo email (principal) de seu Delegado associado
  - [x] editar (update) Escola pelo email (principal) de seu Delegado associado
  - [ ] enviar e-mail para Administradores do sistema avisando que determinado Delegado deseja ter sua conta excluída 
- [x] Repository Escola
  - [x] buscar Escola pelo email de seu Delegado associado 

<sub>* informação recuperada diretamente do token, injetada via [próprio Spring Boot](https://www.baeldung.com/get-user-in-spring-security#controller)</sub>
